import { url } from "./index";

// console.log(url);

export let restaurantList = [
  {
    name: "KFC",
    id: 1234,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹400 for two",
    cuisines: ["Pizza", "Italian", "Fast food"],
    image: url.KFC,
    avgRating: 3.8,
    veg: false,
    deliveryTime: 30,
  },
  {
    name: "Dominos",
    id: 1235,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹450 for two",
    cuisines: ["Pizza", "Italian", "Fast food"],
    image: url.Dominos,
    avgRating: 4.6,
    veg: false,
    deliveryTime: 30,
  },
  {
    name: "McDonald's",
    id: 1236,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹360 for two",
    cuisines: ["Burger", "Italian", "Fast food"],
    image: url.McDonalds,
    avgRating: 4.1,
    veg: false,
    deliveryTime: 30,
  },
  {
    name: "Pizza hut",
    id: 1237,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹380 for two",
    cuisines: ["Pizza", "Italian", "Fast food"],
    image: url.PizzaHut,
    avgRating: 3.7,
    veg: false,
    deliveryTime: 30,
  },
  {
    name: "A.M Biriyani",
    id: 1238,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹800 for two",
    cuisines: ["Biriyani", "Fast food"],
    image: url.AMBiriyani,
    avgRating: 4.7,
    veg: false,
    deliveryTime: 30,
  },
  {
    name: "Kasthoori coffee",
    id: 1239,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹800 for two",
    cuisines: ["South-indian", "Fast food"],
    image: url.Kasthoori,
    avgRating: 4.7,
    veg: false,
    deliveryTime: 30,
  },
];
