export let restaurantList = [
  {
    name: "KFC",
    id: 1234,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹400 for two",
    cuisines: ["Pizza", "Italian", "Fast food"],
    image:
      "https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg",
    avgRating: 3.8,
    veg: false,
    deliveryTime: 30,
  },
  {
    name: "Dominos",
    id: 1235,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹450 for two",
    cuisines: ["Pizza", "Italian", "Fast food"],
    image: "https://images.pexels.com/photos/166451/pexels-photo-166451.jpeg",
    avgRating: 4.6,
    veg: false,
    deliveryTime: 30,
  },
  {
    name: "McDonald's",
    id: 1236,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹360 for two",
    cuisines: ["Burger", "Italian", "Fast food"],
    image: "https://images.pexels.com/photos/2282528/pexels-photo-2282528.jpeg",
    avgRating: 4.1,
    veg: false,
    deliveryTime: 30,
  },
  {
    name: "Pizza hut",
    id: 1237,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹380 for two",
    cuisines: ["Pizza", "Italian", "Fast food"],
    image: "https://images.pexels.com/photos/6068711/pexels-photo-6068711.jpeg",
    avgRating: 3.7,
    veg: false,
    deliveryTime: 30,
  },
  {
    name: "A.M Biriyani",
    id: 1238,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹800 for two",
    cuisines: ["Biriyani", "Fast food"],
    image: "https://images.pexels.com/photos/12392831/pexels-photo-12392831.jpeg",
    avgRating: 4.7,
    veg: false,
    deliveryTime: 30,
  },
  {
    name: "Kasthoori coffee",
    id: 1239,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹800 for two",
    cuisines: ["South-indian", "Fast food"],
    image: "https://images.pexels.com/photos/9619560/pexels-photo-9619560.jpeg",
    avgRating: 4.7,
    veg: false,
    deliveryTime: 30,
  }
];