import {
  AMBiriyani,
  Dominos,
  Kasthoori,
  KFC,
  McDonalds,
  PizzaHut,
} from "./urlLinks";

export let restaurantList = [
  {
    name: "KFC",
    id: 1234,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹400 for two",
    cuisines: ["Pizza", "Italian", "Fast food"],
    image: KFC,
    avgRating: 3.8,
    veg: false,
    deliveryTime: 30,
  },
  {
    name: "Dominos",
    id: 1235,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹450 for two",
    cuisines: ["Pizza", "Italian", "Fast food"],
    image: Dominos,
    avgRating: 4.6,
    veg: false,
    deliveryTime: 30,
  },
  {
    name: "McDonald's",
    id: 1236,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹360 for two",
    cuisines: ["Burger", "Italian", "Fast food"],
    image: McDonalds,
    avgRating: 4.1,
    veg: false,
    deliveryTime: 30,
  },
  {
    name: "Pizza hut",
    id: 1237,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹380 for two",
    cuisines: ["Pizza", "Italian", "Fast food"],
    image: PizzaHut,
    avgRating: 3.7,
    veg: false,
    deliveryTime: 30,
  },
  {
    name: "A.M Biriyani",
    id: 1238,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹800 for two",
    cuisines: ["Biriyani", "Fast food"],
    image: AMBiriyani,
    avgRating: 4.7,
    veg: false,
    deliveryTime: 30,
  },
  {
    name: "Kasthoori coffee",
    id: 1239,
    locality: "MG Road",
    areaName: "Central District",
    costForTwo: "₹800 for two",
    cuisines: ["South-indian", "Fast food"],
    image: Kasthoori,
    avgRating: 4.7,
    veg: false,
    deliveryTime: 30,
  },
];
